# This is a basic workflow that is manually triggered

name: Manual publish website using FTP

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Greeting
      run: echo "Deploying website..."
    - name: Checkout code
      uses: actions/checkout@v2
    - name: My location
      run: pwd
    - name: My location
      run: ls
    - name: Install FTP client
      run: sudo apt-get install lftp
    - name: Copy via FTP
      run: lftp -e "mirror -R /home/runner/work/egallo.com.ar/egallo.com.ar/public_html/ /" -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }}

 
